### PR TITLE
The task 1 for backend development using node is completed.

### PR DESCRIPTION
**Pull request by barsha119**

### CODE REVIEW

**Comment by chandrasekhar2039** [comment]
Host it in a Public server. And paste the link in the description. It will be inconvenience for us to check everything in local host.

**Review by chandrasekhar2039 — CHANGES_REQUESTED** [review]
Host it in a Public server. And paste the link in the description. It will be inconvenience for us to check everything in local host. And don't change the original [readme](https://github.com/EnigmaVSSUT/induction-2021-2nd-yr/tree/main/Backend%20Development%20using%20Node/Task%20Submission) Create a new readme in your respective folder explaining your implementation.

**Comment by barsha119** [comment]
Ok

**Review by chandrasekhar2039 — CHANGES_REQUESTED** [review]
image

Provide a minimum parameter to submit the number of quotes. if i choose zero it sends no data

**Review by chandrasekhar2039 — APPROVED** [review]

**Pull request merged**
